export { default as Box } from './components/shared/Box';
export { default as Text } from './components/shared/Text';
export { default as theme } from './theme/theme';
export { GameProvider, useGame } from './context/GameContext';
export type { Theme } from './theme/theme';

export { default as SplashScreen } from './screens/SplashScreen';
export { default as MainMenuScreen } from './screens/MainMenuScreen';
export { default as HostModeScreen } from './screens/HostModeScreen';
export { default as AgeSelectionScreen } from './screens/AgeSelectionScreen';
export { default as DifficultySelectionScreen } from './screens/DifficultySelectionScreen';
export { default as QuestionTypeScreen } from './screens/QuestionTypeScreen';
export { default as TurnTimerScreen } from './screens/TurnTimerScreen';
export { default as PlayerSetupScreen } from './screens/PlayerSetupScreen';
export { default as GameScreen } from './screens/GameScreen';
export { default as TruthOrDareScreen } from './screens/TruthOrDareScreen';
export { default as QuestionScreen } from './screens/QuestionScreen';
export { default as SettingsScreen } from './screens/SettingsScreen';
export { default as RulesScreen } from './screens/RulesScreen';
export { default as SoundScreen } from './screens/SoundScreen';
export { default as LanguageScreen } from './screens/LanguageScreen';
export { default as GameOverScreen } from './screens/GameOverScreen';
